# Singular Value Decomposition (SVD)

This technique factorizes a matrix  $A$  into three matrices: $A = U \Sigma V^T $, where:

- $U $ is an orthogonal matrix whose columns are the left singular vectors.
- $ \Sigma $ is a diagonal matrix whose elements are the singular values.
- $V^T$ (the transpose of $V$ ) is an orthogonal matrix whose columns are the right singular vectors.


This technique can be applied ot any $m \times n$


### Let's generate any random matrix first

In [31]:
import numpy as np

# Create any matrix m x n
m= 5 # Number of rows
n= 6 # Number of columns

A = np.random.uniform(-100,100, size=(m, n)).round(2)

print(A)


[[-72.48 -51.65 -13.96 -40.09  82.51 -68.92]
 [-14.5   25.71 -10.98 -23.1  -15.71  28.96]
 [ 99.75   1.98 -32.94 -46.89 -39.18 -17.96]
 [ 37.83 -39.62  73.23  37.87 -15.79 -97.91]
 [ 36.53  -2.15 -36.46  -9.72 -97.63  -1.49]]


In [32]:
def svd_manual(matrix):
    # Step 1: Calculate A^T * A
    A_AT = np.dot(matrix.T, matrix)

    # Step 2: Eigen decomposition of A^T * A
    eigenvalues, eigenvectors = np.linalg.eig(A_AT)

    # Step 3: Sort eigenvalues and eigenvectors in descending order
    sorted_indices = np.argsort(eigenvalues)[::-1]
    eigenvalues_sorted = eigenvalues[sorted_indices]
    eigenvectors_sorted = eigenvectors[:, sorted_indices]

    # Step 4: Calculate singular values sigma
    sigma = np.sqrt(eigenvalues_sorted)
    S = np.diag(sigma)

    # Step 5: Calculate matrix U
    U = eigenvectors_sorted

    # Step 6: Calculate matrix V
    #V = np.dot(matrix.T, U) / sigma
    # Step 6: Calculate matrix V
    V = np.dot(np.linalg.inv(S), np.dot(U.T, matrix.T))
    # Reconstruct the original matrix A
    A_reconstructed = U @ S @ V

    # Print results
    print('ORIGINAL GENERATED MATRIX \n', A)
    print('This is the U MATRIX \n', U)
    print('This is S MATRIX\n', S)
    print('This is V MATRIX\n', V)
    print('\n\nFINALLY OUR RECONSTRUCTED A MATRIX \n', A_reconstructed.T)

    return U, S, V.T

In [33]:
U,S,Vt = svd_manual(A)

ORIGINAL GENERATED MATRIX 
 [[-72.48 -51.65 -13.96 -40.09  82.51 -68.92]
 [-14.5   25.71 -10.98 -23.1  -15.71  28.96]
 [ 99.75   1.98 -32.94 -46.89 -39.18 -17.96]
 [ 37.83 -39.62  73.23  37.87 -15.79 -97.91]
 [ 36.53  -2.15 -36.46  -9.72 -97.63  -1.49]]
This is the U MATRIX 
 [[-0.61673968 -0.39577957  0.13592612  0.63311504  0.20477788  0.04178706]
 [-0.22113428  0.3277385  -0.2197761   0.24255215 -0.49328106 -0.7023018 ]
 [ 0.1737364  -0.38348856 -0.58229955  0.20181463 -0.5359017   0.39466396]
 [ 0.03088048 -0.16251605 -0.6980312  -0.09654412  0.60748547 -0.32715136]
 [ 0.68730739  0.13293598  0.11427093  0.67272786  0.18978232 -0.09109679]
 [-0.25923428  0.73810506 -0.30634032  0.19421925  0.14997752  0.48367317]]
This is S MATRIX
 [[1.84657173e+02 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.48958215e+02 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.01368097e+02 0.00000000e+00
  